apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demoApps.fullname" . }}-php-flight
  labels:
    {{- include "demoApps.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.phpFlight.replicas }}
  selector:
    matchLabels:
      app: {{ include "demoApps.name" . }}-php-flight
      {{- include "demoApps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.phpFlight.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "demoApps.name" . }}-php-flight
        {{- include "demoApps.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: php-flight
          image: {{ .Values.phpFlight.image }}
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: {{ include "demoApps.fullname" . }}-mysql
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: {{ include "demoApps.db.password" . }}
            - name: DB_DATABASE
              value: test