{{- if .Values.phpFlight.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demoApps.fullname" . }}-php-flight
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ include "demoApps.name" . }}-php-flight
{{- end }}