apiVersion: v1
kind: Service
metadata:
  name: {{ include "demoApps.fullname" . }}-java-sb
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ include "demoApps.name" . }}-java-sb
