ingress:
  enabled: true
  annotations: {}
  className: nginx
  hosts: demo.example.com
  tls: []

javaSb:
  image: flyingsnake12/demo-java-springboot:1.0.1
  replicas: 1
  podAnnotations: {}

nodejsExpress:
  image: flyingsnake12/demo-nodejs-express:1.0.1
  replicas: 1
  podAnnotations: {}

golangEcho:
  image: flyingsnake12/demo-golang-echo:1.0.1
  replicas: 1
  podAnnotations: {}

phpFlight:
  image: flyingsnake12/demo-php-flight:1.0.1
  replicas: 1
  podAnnotations: {}

mysql:
  image: flyingsnake12/demo-mysql:1.0.0
  env:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: test