{{- if .Values.ingress.enabled -}}
{{- $fullName := include "demoApps.fullname" . -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "demoApps.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hosts }}
      http:
        paths:
          {{- if .Values.frontWeb.enabled }}
          - path: /dotnet(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "demoApps.fullname" . }}-dotnet-carter
                port:
                  number: 80
              {{- else }}
              serviceName: {{ include "demoApps.fullname" . }}-dotnet-carter
              servicePort: 80
              {{- end }}
          {{- end }}
         {{- if .Values.javaSb.enabled }}
          - path: /java(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "demoApps.fullname" . }}-java-sb
                port:
                  number: 80
              {{- else }}
              serviceName: {{ include "demoApps.fullname" . }}-java-sb
              servicePort: 80
              {{- end }}
          {{- end }}
          {{- if .Values.nodejsExpress.enabled }}
          - path: /nodejs(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "demoApps.fullname" . }}-nodejs-express
                port:
                  number: 80
              {{- else }}
              serviceName: {{ include "demoApps.fullname" . }}-nodejs-express
              servicePort: 80
              {{- end }}
          {{- end }}
          {{- if .Values.phpFlight.enabled }}
          - path: /php(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "demoApps.fullname" . }}-php-flight
                port:
                  number: 80
              {{- else }}
              serviceName: {{ include "demoApps.fullname" . }}-php-flight
              servicePort: 80
              {{- end }}
          {{- end }}
          {{- if .Values.golangEcho.enabled }}
          - path: /golang(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "demoApps.fullname" . }}-golang-echo
                port:
                  number: 80
              {{- else }}
              serviceName: {{ include "demoApps.fullname" . }}-golang-echo
              servicePort: 80
              {{- end }}
          {{- end }}
          {{- if .Values.pythonFlask.enabled }}
          - path: /python(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "demoApps.fullname" . }}-python-flask
                port:
                  number: 80
              {{- else }}
              serviceName: {{ include "demoApps.fullname" . }}-python-flask
              servicePort: 80
              {{- end }}
          {{- end }}
          {{- if .Values.dotnetCarter.enabled }}
          - path: /dotnet(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "demoApps.fullname" . }}-dotnet-carter
                port:
                  number: 80
              {{- else }}
              serviceName: {{ include "demoApps.fullname" . }}-dotnet-carter
              servicePort: 80
              {{- end }}
          {{- end }}
{{- end }}
