{{- if .Values.golangEcho.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demoApps.fullname" . }}-golang-echo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ include "demoApps.name" . }}-golang-echo
{{- end }}