apiVersion: v1
kind: Service
metadata:
  name: {{ include "demoApps.fullname" . }}-nodejs-express
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: {{ include "demoApps.name" . }}-nodejs-express
