{{- if .Values.pythonFlask.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demoApps.fullname" . }}-python-flask
  labels:
    {{- include "demoApps.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pythonFlask.replicas }}
  selector:
    matchLabels:
      app: {{ include "demoApps.name" . }}-python-flask
      {{- include "demoApps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.pythonFlask.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "demoApps.name" . }}-python-flask
        {{- include "demoApps.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: python-flask
          image: {{ .Values.pythonFlask.image }}
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: {{ include "demoApps.fullname" . }}-mysql
            - name: DB_USERNAME
              value: {{ include "demoApps.db.username" .}}
            - name: DB_PASSWORD
              value: {{ include "demoApps.db.password" . }}
            - name: DB_DATABASE
              value: {{ include "demoApps.db.database" . }}
{{- end }}