{{- if .Values.pythonFlask.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demoApps.fullname" . }}-python-flask
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: {{ include "demoApps.name" . }}-python-flask
{{- end }}