{{- if .Values.dotnetCarter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demoApps.fullname" . }}-dotnet-carter
  labels:
    {{- include "demoApps.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dotnetCarter.replicas }}
  selector:
    matchLabels:
      app: {{ include "demoApps.name" . }}-dotnet-carter
      {{- include "demoApps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.dotnetCarter.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "demoApps.name" . }}-dotnet-carter
        {{- include "demoApps.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: dotnet-carter
          image: {{ .Values.dotnetCarter.image }}
          ports:
            - containerPort: 8085
          env:
            - name: DB_HOST
              value: {{ include "demoApps.fullname" . }}-mysql
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: {{ include "demoApps.db.password" . }}
            - name: DB_DATABASE
              value: test
{{- end }}