{{- if .Values.dotnetCarter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demoApps.fullname" . }}-dotnet-carter
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8085
  selector:
    app: {{ include "demoApps.name" . }}-dotnet-carter
{{- end }}